[tox]
envlist = mypy, py310, py311, py312, py313
requires =
    tox-uv

[testenv:mypy]
runner = uv-venv-lock-runner
description = run type checker via mypy
commands =
    mypy meilisearch

[testenv]
runner = uv-venv-lock-runner
description = run tests
commands =
    pytest
