name: PyPI

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
      PYTHON_VERSION: "3.10"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check release validity
        run: sh .github/scripts/check-release.sh

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          version: "0.11.21"
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: false

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: "pypi-${{ secrets.PYPI_API_TOKEN }}"
        run: |
          uv build
          uvx twine@6.2.0 upload dist/*
